require 'set_attributes/controls/object'
require 'set_attributes/controls/hash'
require 'set_attributes/controls/hashish'
require 'set_attributes/controls/attribute_map'
require 'set_attributes/controls/data_source'
