require 'set_attributes/controls/object'
require 'set_attributes/controls/hash'
require 'set_attributes/controls/hashish'
require 'set_attributes/controls/mapping'
require 'set_attributes/controls/data_source'
